# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: polats.github.io
email: paulgadi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Paul Gadi | Altitude Games | VR, Game Development
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://polats.github.io" # the base hostname & protocol for your site
twitter_username: polats
github_username:  polats
# Build settings
markdown: kramdown
gems:
   - jemoji
