#!/bin/bash
echo "-- sudo apt-get update"
echo "------------------------------------"
sudo apt-get update
echo "-- sudo apt-get install ruby requirements"
echo "------------------------------------"
sudo apt-get install git-core curl zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev python-software-properties libffi-dev -y
echo "-- install ruby"
echo "------------------------------------"
cd
git clone https://github.com/rbenv/rbenv.git ~/.rbenv
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
echo 'eval "$(rbenv init -)"' >> ~/.bashrc

git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
echo 'export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"' >> ~/.bashrc

~/.rbenv/bin/rbenv install 2.2.5
~/.rbenv/bin/rbenv global 2.2.5
ruby -v
gem install bundler

mkdir -m 700 /root/.ssh
cp ~vagrant/.ssh/authorized_keys /root/.ssh
